### ISSUE TITLE
some data is not available now

### ISSUE THREAD

**Issue by RasinGue** [DSKSD/cs-224n-Pytorch#6]
`
download dependency parser dataset... (clone from https://github.com/rguthrie3/DeepDependencyParsingProblemSet
mkdir: created directory '../dataset/dparser'
--2018-03-02 15:08:08--  https://raw.githubusercontent.com/rguthrie3/DeepDependencyParsingProblemSet/master/data/train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.12.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-02 15:08:09 ERROR 404: Not Found.

--2018-03-02 15:08:09--  https://raw.githubusercontent.com/rguthrie3/DeepDependencyParsingProblemSet/master/data/vocab.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.12.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-02 15:08:09 ERROR 404: Not Found.

--2018-03-02 15:08:09--  https://raw.githubusercontent.com/rguthrie3/DeepDependencyParsingProblemSet/master/data/dev.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.12.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-02 15:08:09 ERROR 404: Not Found.
`

It seems like @rguthrie3 has deleted the repo... Could you please update a new address for us? Thanks!

**Comment by rguthrie3** [comment]
Sorry, didn’t know anybody was using it.  A copy of the problem set is available still on the class GitHub I wrote it for here

https://github.com/jacobeisenstein/gt-nlp-class/tree/master/2017-materials/psets/ps4
